author:
  name: Abraheem Khouqeer
  email: Abraheem.khouqeer@vanderbilt.edu


remote_theme: jekyll/minima

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/Ferrell-Lab/" }
